### PR TITLE
Add Vite as build tool

### PR DESCRIPTION
**Pull request by tung-eh**
Issue #9 

Add build tool

### CODE REVIEW

**Comment by tung-eh** [comment]
Prettier made a lot of changes, I will add prettier config to another pull request, we should merge that one first.

**Comment by tung-eh** [comment]
Prettier config PR https://github.com/canhnd58/duosnake/pull/15

**Comment by canhnd58** [comment]
10 billion points.

Can you split `main.js` into at least 2 files and/or folders for those unfamiliar with Vite (me) to know how to continue coding?

**Comment by tung-eh** [comment]
@canhnd58 Vite using ES module syntax, it means using we can use `import`/`export` to communicate between modules.

For example
```javascript
// foo.js
const a = 'some string'
const b = 'some other string'

export { a }
export default b
```

```javascript
// bar.js

import { a }, b from './foo' /* Let say foo.js in the same dir with bar.js */
```

**Pull request merged**
